### PR TITLE
Increments gosheets to v1.0.0

### PR DESCRIPTION
**Pull request by AlexOverbeck**
# V1.0.0 http://www.tangoe.design/standards
# 🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

### CODE REVIEW

**Review by devchris — APPROVED** [review]
🥇

**Review by grahamhency — APPROVED** [review]
Exciting stuff, I think I'm good with this, but I've been using it for awhile so I might be biased.

**Review by jaredami — APPROVED** [review]
👏

**Review by StevenUlmer — APPROVED** [review]
💯

**Pull request merged**
